name: Sample Workflow Two

  
on:
  workflow_dispatch:
    inputs:
      better_dispatch_form:
        type: string
        required: false
        default: .github/better_dispatch/sample_form_two.json
jobs:
  log-form-data:
    runs-on: ubuntu-latest
    steps:
      - name: Display Form Output
        run: |
          echo "Form file: ${{ inputs.better_dispatch_form }}"
