// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./pkg/config/models.js";

/**
 * @returns {$CancellablePromise<string>}
 */
export function ChooseDir() {
    return $Call.ByID(12415951);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ClearClipboard() {
    return $Call.ByID(747885572);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteNote(id) {
    return $Call.ByID(1615155726, id);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function GetClipData(name) {
    return $Call.ByID(1261390009, name);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetNotes() {
    return $Call.ByID(84666500);
}

/**
 * @returns {$CancellablePromise<config$0.Settings>}
 */
export function GetSettings() {
    return $Call.ByID(2554697378).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Quit() {
    return $Call.ByID(3181047470);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function RegisterHotKey() {
    return $Call.ByID(4020475874);
}

/**
 * @param {string} content
 * @returns {$CancellablePromise<string>}
 */
export function SaveNote(content) {
    return $Call.ByID(717593036, content);
}

/**
 * @param {config$0.Settings | null} settings
 * @returns {$CancellablePromise<boolean>}
 */
export function SaveSettings(settings) {
    return $Call.ByID(1949631069, settings);
}

/**
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApplication(app) {
    return $Call.ByID(4121261467, app);
}

/**
 * @param {application$0.WebviewWindow | null} window
 * @returns {$CancellablePromise<void>}
 */
export function SetMainWindow(window) {
    return $Call.ByID(843697430, window);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Toggle() {
    return $Call.ByID(1190013837);
}

/**
 * @param {string} hash
 * @returns {$CancellablePromise<void>}
 */
export function ToggleClipSecret(hash) {
    return $Call.ByID(3964646531, hash);
}

/**
 * @param {string} id
 * @param {string} content
 * @returns {$CancellablePromise<string>}
 */
export function UpdateNote(id, content) {
    return $Call.ByID(3719758856, id, content);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function WindowHide() {
    return $Call.ByID(2361993597);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function WindowShow() {
    return $Call.ByID(3381873996);
}

// Private type creation functions
const $$createType0 = config$0.Settings.createFrom;
